plugins {
  id 'application'
}

mainClassName = "com.selesse.tailerswift.Main"
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
  implementation('com.google.guava:guava:16.0')
  runtimeOnly('org.slf4j:slf4j-api:1.7.32')
  implementation('ch.qos.logback:logback-classic:1.2.10')

  testImplementation 'commons-io:commons-io:2.4'
  testImplementation 'org.assertj:assertj-swing-junit:3.17.1'
  testImplementation 'junit:junit:4.11'
}

jar {
    manifest {
        attributes 'Manifest-Version': version, 'Main-Class': mainClassName
    }
}
